version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: pmc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - pmc_network

  gearmand:
    image: dockage/gearmand
    container_name: pmc_gearman
    depends_on:
      - app
    networks:
      - pmc_network

  # http://localhost:25672/#/queues
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pmc_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    depends_on:
      - app
    ports:
      - "25672:15672" # web interface
    networks:
      - pmc_network

  redis:
    image: redis:7.4
    container_name: pmc_redis
    #ports:
    #  - "6379:6379"
    depends_on:
      - app
    networks:
      - pmc_network

#  socket:
#    image: node
#    container_name: pmc_socket
#    user: "node"
#    volumes:
#      - ./src/socket:/home/node/app
#    ports:
#      - "5005:5000"
#    working_dir: /home/node/app
#    command: "npm start"

  nginx:
    image: nginx:1.23.4
    container_name: pmc_nginx
    volumes:
      - ./docker/nginx/conf/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/conf/sites-enabled/pmc.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - pmc_network

#  db:
#    image: mysql:8.0.33
#    container_name: pmc_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: pmc
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: root
#    ports:
#      - "3308:3306"
#    networks:
#      - pmc_network
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql

networks:
  pmc_network:
    driver: bridge