version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: pmc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - pmc_network
    environment:
      DATABASE_URL: mysql://admin:root@db:3308/pmc

  db:
    image: mysql:8.0.33
    container_name: pmc_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pmc
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - pmc_network
    volumes:
      - ./docker/mysql:/var/lib/mysql

  nginx:
    image: nginx:1.23.4
    container_name: pmc_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - pmc_network

networks:
  pmc_network:
    driver: bridge