version: '3.9'

services:
  app:
    image: php:8.4-fpm
#    build:
#      context: .
#      dockerfile: ./docker/php/Dockerfile
    container_name: pmc_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
#    ports:
#      - "9001:9001"
#    networks:
#      - pmc_network

  nginx:
    image: nginx:1.23.4
    container_name: pmc_nginx
    volumes:
      - ./docker/nginx/conf/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/conf/sites-enabled/pmc.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
#    networks:
#      - pmc_network

#  db:
#    image: mysql:8.0.33
#    container_name: pmc_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: pmc
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: root
#    ports:
#      - "3308:3306"
#    networks:
#      - pmc_network
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql

#networks:
#  pmc_network:
#    driver: bridge